language: php

php:
    - 5.3
    - 5.4
    - 5.5

branches:
    only:
        - master

cache:
    directories:
        - /home/travis/.composer/cache

matrix:
    fast_finish: true

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update

install:
    - composer install

script:
    - php -l lib
    - bin/phpcs lib --standard=PSR2 --extensions=php
    - bin/phpmd lib text build/phpmd.xml
    - bin/phpunit
